title: "もるらぼ -GuineaPigLab-"
description: "もるらぼ -GuineaPigLab- は、モルモットと一緒に暮らす際に役立つ情報を某飼い主が提供するサイトです。"
keywords: "もるらぼ, モルモット研究室, モルモットを飼育するための実用書, モルモット, mimolme, Guinea pig Laboratory, モルモットの飼い方, モルモットと暮らしたい, モルモットの飼育方法, モルモット 観察, モルモット 健康, モルモット 病気, モルモット 環境, モルモット 食べ物, モルモット 豆乳, モルモット 羊毛フェルト"
url: "https://mimolme.github.io"
baseurl: ""
lang: ja

# G-TAG
ga_measurement_id: "G-85BH18E352"

# GitHub Pagesで使えるSEOプラグイン
plugins:
- jekyll-seo-tag
